package com.example.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "properties")
public class Property {

    private String id;
    private String nameOfOwner;
    private String contact;
    private String state;
    private String location;
    private String propertyToBe;
    private Double cost;
    private String description;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    @DynamoDBAttribute(attributeName = "name_of_owner")
    public String getNameOfOwner() { return nameOfOwner; }
    public void setNameOfOwner(String nameOfOwner) { this.nameOfOwner = nameOfOwner; }

    @DynamoDBAttribute(attributeName = "contact")
    public String getContact() { return contact; }
    public void setContact(String contact) { this.contact = contact; }

    @DynamoDBAttribute(attributeName = "state")
    public String getState() { return state; }
    public void setState(String state) { this.state = state; }

    @DynamoDBAttribute(attributeName = "location")
    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }

    @DynamoDBAttribute(attributeName = "property_to_be")
    public String getPropertyToBe() { return propertyToBe; }
    public void setPropertyToBe(String propertyToBe) { this.propertyToBe = propertyToBe; }

    @DynamoDBAttribute(attributeName = "cost")
    public Double getCost() { return cost; }
    public void setCost(Double cost) { this.cost = cost; }

    @DynamoDBAttribute(attributeName = "description")
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
}
