package com.example.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "roles")
public class Roles {
    private String id;
    private int role;
    private Menus menus;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    @DynamoDBAttribute(attributeName="role")
    public int getRole() { return role; }
    public void setRole(int role) { this.role = role; }

    @DynamoDBAttribute(attributeName="menus")
    public Menus getMenus() { return menus; }
    public void setMenus(Menus menus) { this.menus = menus; }

    @Override
    public String toString() {
        return "Roles [id=" + id + ", role=" + role + ", menus=" + menus + "]";
    }
}